# Generated by Django 2.0.6 on 2018-06-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
                ('body', models.CharField(max_length=1000)),
            ],
        ),
    ]
